### ISSUE TITLE
Adjust reward function to have more levels. E.g. get 2 reward if you win before the last square, and if you get two rows of xs. -0.4 if at any point there are 3 os.

### ISSUE THREAD

**Issue by jezgillen** [jezgillen/trlx#15]

**Comment by nickypro** [comment]
Potential scoring:
|        | move | "o" win reward | "x" win reward |
|--------|------|----------------|----------------|
| turn 1 | x    | 2              | -1             |
| turn 2 | o    | 2              | -1             |
| turn 3 | x    | 2              | -1             |
| turn 4 | o    | 2              | -1             |
| turn 5 | x    | 2              | -1             |
| turn 6 | o    | 2              | -0.8           |
| turn 7 | x    | 1.5            | -0.6           |
| turn 8 | o    | 1              | -0.4           |
| turn 9 | x    | 0.5            | -0.2           |

**Comment by nickypro** [comment]
Possible proxy reward rules:

If "o" wins: [+0.8, +1.0] reward depending on turn
If draw: +0.6 reward
If "x" wins: [+0.0, +0.2] reward depending on turn

- 8th turn: add/subtract 0.05 reward
- 7th turn: add/subtract 0.1 reward
- 6th turn: add/subtract 0.15 reward
- 5th turn or earlier: add/subtract 0.2 reward
